version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client_container
    volumes:
      - ./client:/app
      - /app/node_modules
    ports: 
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: server_container
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=to_do_list

    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data    

volumes:
  db_data: 